[package]
name = "makepad-live-tokenizer"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

#See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
makepad-math = { path = "../math", version = "0.1" }
makepad-micro-serde = { path = "../micro_serde", version = "0.1" }
makepad-live-id = { path = "../live_id", version = "0.1"}
