[package]
name = "makepad-live-id"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

[dependencies]
makepad-id-macros = { path = "id_macros", version = "0.1" }
makepad-error-log = { path = "../error_log", version = "0.1" }
